Add hap blog post
vvvv/visualprogramming.net pull request #7
Opened 2022-04-11 21:14 UTC by leavittx

I'm using links to images hosted on github

2022-04-15 08:58 UTC, leavittx commented
Test comment

2022-04-18 13:53 UTC, antongit commented
Test comment

2022-04-18 13:53 UTC, joreg requested changes

2022-04-18 14:19 UTC, joreg requested changes

2022-04-18 14:19 UTC, joreg commented on content/blog/2022/other/news_in_hap_world.md
> +There were multiple important things happening in the Hap GPU-accelerated video playback codec world recently. Sadly, there is no a single website with all these updates (though there is an [official
_not_ a single website..

2022-04-18 14:19 UTC, joreg commented on content/blog/2022/other/news_in_hap_world.md
> +2. The loop playback has became seamless (thanks to pre-caching next frames in a non-stop manner). No hiccups at the start of new loop whether you have custom start/end frames set or not
has _become_ seamless

2022-04-18 14:19 UTC, joreg commented on content/blog/2022/other/news_in_hap_world.md
> +Update: for users unable to use Patreon there is a [Boosty page](https://boosty.to/hap_player) now.
Consider removing the "Update" because it is anyway the first post now?!

2022-04-18 17:49 UTC, leavittx commented on content/blog/2022/other/news_in_hap_world.md
> +2. The loop playback has became seamless (thanks to pre-caching next frames in a non-stop manner). No hiccups at the start of new loop whether you have custom start/end frames set or not
oh, right

2022-04-18 18:00 UTC, joreg approved these changes

2022-04-20 07:41 UTC, merged